### Obtención de todos los productos
GET http://localhost:1234/productos/

### Obtención de un producto específico
GET http://localhost:1234/productos/3/

### Agregado de un producto nuevo
POST http://localhost:1234/productos/
Content-Type: application/json

{
    "id": 11,
    "nombre": "Mixer multiuso ACME",
    "tipo": "Electrodoméstico de cocina",
    "precio": 150.15
}

### Actualización de un producto
PATCH http://localhost:1234/productos/10
Content-Type: application/json

{
    "nombre": "Mixer multiuso ACME PODEROSO"
}

### Borrado de un producto
DELETE http://localhost:1234/productos/8

### Obtención de todos los usuarios
GET http://localhost:1234/usuarios/

### Obtención de un usuario específico
GET http://localhost:1234/usuarios/2/

### Agregado de un usuario nuevo
POST http://localhost:1234/usuarios/
Content-Type: application/json

{
    "id": 11,
    "nombre": "Nuevo Usuario",
    "edad": 35,
    "email": "nuevo@example.com",
    "telefono": "+1 987-654-3210"
}

### Actualización de un usuario
PATCH http://localhost:1234/usuarios/10
Content-Type: application/json

{
    "nombre": "Usuario Modificado"
}

### Borrado de un usuario
DELETE http://localhost:1234/usuarios/7

### Obtención del total del stock de productos
GET http://localhost:1234/productos/total

### Obtención del nombre de un producto por ID
GET http://localhost:1234/productos/nombre/2

### Obtención del teléfono de un usuario por ID
GET http://localhost:1234/usuarios/telefono/3

### Obtención del nombre de un usuario por ID
GET http://localhost:1234/usuarios/nombre/5
